env:
  global:
    CC_TEST_REPORTER_ID_=02a83fd4e0af48eec13c20dc5affeb43719d6913cb0237a0ec141bac68570214
language: node_js

node_js:
  - node

script:
  - make lint
  - make test

after_script:
  - ./cc-test-reporter format-coverage -t lcov ./coverage/lcov.info
  - ./cc-test-reporter -d after-build --exit-code $TRAVIS_TEST_RESULT
